### ISSUE TITLE
model.predict throwing an error

### ISSUE THREAD

**Issue by saramcardle** [CSBDeep/CSBDeep#6] opened 2018-06-19 17:48 UTC
I've recently installed CSBDeep through the docker. When I run the 3rd .ipynb file from the denoising3D example, in cell 5 (prediction from the original noisy data), I get this error:

```
InternalError: Dst tensor is not initialized.
	 [[Node: _arg_input_0_0/_133 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_201__arg_input_0_0", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
	 [[Node: activation_1/Identity/_135 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_203_activation_1/Identity", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```
(full error message attached)   
[denoising3D error.txt](https://github.com/CSBDeep/CSBDeep/files/2116259/denoising3D.error.txt).

The terminal window says this:
```
8] Sum Total of in-use chunks: 3.81MiB
2018-06-19 16:49:08.393798: I tensorflow/core/common_runtime/bfc_allocator.cc:680] Stats: 
Limit:                    90439680
InUse:                     3993856
MaxInUse:                  6538496
NumAllocs:                      72
MaxAllocSize:               884736
```

If I try cell 6 instead, with n_tiles=16, it hangs forever trying larger and larger tile numbers. This is also what happens if I call the function with n_tiles=1. 

I'm new to tensorflow, so I'm not sure how to debug this. I've installed the latest nvidia driver (390.67). I'm running Ubuntu 18.04, with a GeForce GTX 1080 gpu. The training step in this example, and the entire denoising2D example, worked great.

Thanks!

**Comment by uschmidt83** [comment] 2018-06-19 18:03
Hi, my first guess is that TensorFlow is probably out of GPU memory.
Maybe you still have the training (or another) notebook open? If so, try shutting it down.

Use the command-line tool `nvidia-smi` ([link](https://developer.nvidia.com/nvidia-system-management-interface)) to debug problems like this, which should have been automatically installed with the drivers (or CUDA). With it, you can see all processes that use the GPU and also how much memory is available.

**Comment by saramcardle** [comment] 2018-06-19 19:23
Thank you for your fast response.
I've tried shutting down the other notebooks, but I still have the error. This is the result from nvidia-smi 

sara@Sara-01-3155:~/Documents$ nvidia-smi
Tue Jun 19 12:19:42 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.67                 Driver Version: 390.67                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:02:00.0  On |                  N/A |
| 50%   56C    P8    19W / 240W |    577MiB /  8118MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1471      G   /usr/lib/xorg/Xorg                            30MiB |
|    0      1541      G   /usr/bin/gnome-shell                          49MiB |
|    0      1937      G   /usr/lib/xorg/Xorg                           198MiB |
|    0      2077      G   /usr/bin/gnome-shell                          73MiB |
|    0      2956      G   /usr/lib/firefox/firefox                       2MiB |
|    0      3398      G   /usr/lib/firefox/firefox                       2MiB |
|    0      3938      G   /usr/lib/firefox/firefox                      22MiB |
|    0     10689      C   /usr/bin/python                              187MiB |
+-----------------------------------------------------------------------------+

It looks to me like there is still plenty of GPU memory left?

**Comment by tboo** [comment] 2018-06-19 19:47
Hi -
this is indeed a tensorflow memory issue and is somewhat caused by the nvidia-docker defaults. As you can see in the splash screen of the docker image, once it is loaded:

``NOTE: The SHMEM allocation limit is set to the default of 64MB.  This may be
   insufficient for TensorFlow.  NVIDIA recommends the use of the following flags:
   nvidia-docker run --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 ...
``

Play around with these flags, it should solve your problem.

**Comment by maweigert** [comment] 2019-12-11 12:18
Closing due to non-activity (please reopen if still relevant)

**Closed by maweigert** 2019-12-11 12:18 UTC
